<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Trading.Recorder</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Trading.Application\Trading.Application.csproj" />
    <ProjectReference Include="..\Trading.Domain\Trading.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Trading.Strategies\strategies.json">
      <Link>strategies.json</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
