<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- fuerza a que no cree subcarpeta net10.0 -->
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\Launcher\bin\Debug\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\Launcher\bin\Release\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="pseudo_codigo.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Trading.Strategies.csproj.Backup.tmp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Algorithm\QuantConnect.Algorithm.csproj" />
    <ProjectReference Include="..\Indicators\QuantConnect.Indicators.csproj" />
    <ProjectReference Include="..\Trading.Application\Trading.Application.csproj" />
    <ProjectReference Include="..\Trading.Domain\Trading.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Adapters\" />
  </ItemGroup>

</Project>
